version: '3'
services:

    yumrepo:
      restart: always
      image: centos/7
      container_name: dc_yumrepo
      build:
        context: ./data/Dockerfiles/yumrepo/
        args: 
          - TOKEN=${GITTOKEN}
      volumes:
        - ./data/repos:/repos:rw
      ports:
        - "${HTTP_BIND:-0.0.0.0}:${HTTP_PORT:-8080}:${HTTP_PORT:-8080}" 
      environment:
        - VIRTUAL_HOST=${PUBLIC_FQDN}
        - VIRTUAL_PORT=${HTTP_PORT:-8080}
        - LETSENCRYPT_HOST=${PUBLIC_FQDN}
        - LETSENCRYPT_EMAIL=${ADMIN_MAIL}

